// Generated by CoffeeScript 1.6.3
jQuery(function($) {
  var arr, body, css, flag, gotop, heros, li, nav, obj, scrolling, threed, togClass, win, wrapper;
  win = $(window);
  scrolling = false;
  gotop = $('.gotop');
  body = $('html, body');
  heros = $('.hero-unit');
  nav = $('.nav');
  li = nav.find('li');
  obj = document.createElement('object');
  obj.width = 0;
  obj.height = 0;
  obj.data = 'css/3d.css';
  document.body.appendChild(obj);
  arr = $.map(heros, function(hero) {
    return $(hero).offset().top;
  });
  togClass = function(jqObj) {
    return jqObj.addClass('active').siblings('.active').removeClass();
  };
  win.scroll(function() {
    var temp, top;
    clearTimeout(scrolling);
    top = win.scrollTop();
    scrolling = setTimeout(function() {
      if (top > 200) {
        gotop.fadeIn();
      } else {
        gotop.fadeOut();
      }
    }, 50);
    temp = top + 200;
    if (temp < arr[1]) {
      togClass(li.eq(0));
    } else if (temp <= arr[2]) {
      togClass(li.eq(1));
    } else if (temp <= arr[3]) {
      togClass(li.eq(2));
    } else if (temp <= arr[4]) {
      togClass(li.eq(3));
    } else if (temp <= arr[5]) {
      togClass(li.eq(4));
    }
  });
  gotop.on('click', function() {
    return body.animate({
      'scrollTop': 0
    }, 300);
  });
  threed = $('#threed');
  css = $('#css3d');
  flag = true;
  wrapper = $('.wrapper');
  threed.on('click', function() {
    if (flag) {
      this.innerText = '关闭3D';
      css.attr('href', 'css/3d.css');
    } else {
      this.innerText = '3D导航';
      css.attr('href', '');
      wrapper.removeClass().addClass('wrapper');
    }
    togClass(nav.find('li').eq(0));
    flag = !flag;
    return false;
  });
  nav.on('click', 'li', function() {
    var index, that;
    that = $(this);
    index = that.index();
    togClass(that);
    if (!flag) {
      wrapper.removeClass().addClass('wrapper rotate-' + index);
    } else {
      body.animate({
        'scrollTop': heros.eq(index).offset().top
      }, 300);
    }
  });
});
