// Generated by CoffeeScript 1.6.3
(function() {
  var goTop, goTopIsShown, scrolling;

  goTop = document.querySelector('a.gotop');

  goTopIsShown = scrolling = false;

  window.addEventListener('scroll', function() {
    clearTimeout(scrolling);
    return scrolling = setTimeout(function() {
      var top;
      top = document.body.scrollTop;
      if (top > 100) {
        if (!goTopIsShown) {
          goTop.style.display = 'block';
          return goTopIsShown = true;
        }
      } else if (goTopIsShown) {
        goTop.style.display = 'none';
        return goTopIsShown = false;
      }
    }, 100);
  }, false);

  goTop.addEventListener('click', function() {
    return window.scrollTo(0, 0);
  }, false);

}).call(this);

(function(window){
  var articles = document.getElementsByTagName('article')
  function changePage(){

    var hash = window.location.hash.slice(1)
    if(!hash) return
    hash --
    for (var i = articles.length; i--; ) {
      articles[i].classList.add('hide')
    }
    if(articles[hash]){
      articles[hash].classList.remove('hide')
    } else {
      articles[articles.length - 1].classList.remove('hide')
    }
  }

  window.addEventListener('hashchange', changePage)
  window.addEventListener('DOMContentLoaded', changePage)
}(this));
